export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';
export const SEARCH_ROBOT_PENDING = 'SEARCH_ROBOT_PENDING';
export const SEARCH_ROBOT_SUCCESS = 'SEARCH_ROBOT_SUCCESS';
export const SEARCH_ROBOT_FAILED = 'SEARCH_ROBOT_FAILED';
